/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页列出项目
         * @description 按 createdAt ASC、id ASC 稳定排序。游标绑定租户、过滤条件和排序，
         *     服务端校验完整性；不得包含明文敏感数据。游标有效期 15 分钟。
         *     过期/无效游标返回 400，code=INVALID_CURSOR。
         *     这是实时 keyset 分页，不提供跨页快照保证。nextCursor=null 表示结束。
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * 创建项目
         * @description Idempotency-Key 必填，作用域为租户+主体+operationId。
         *     从终态完成时起保留至少 24 小时；不得按 TTL 清理 IN_PROGRESS/UNKNOWN 状态。
         *     同键同指纹重放原状态、响应体和 Location/ETag；不重做业务写入。
         *     同键不同指纹或原请求仍在执行返回 409，以 code 区分。
         *     创建 displayName 无唯一性要求。description 未提供时存储为空。
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 项目 UUID，按规范小写字符串传输
                 * @example 6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c
                 */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * 查询项目
         * @description 不存在、其他租户或对当前主体不可见的项目均返回 404。
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * 删除项目
         * @description If-Match 校验与删除原子执行。成功返回 204，无响应体、无 Content-Type。
         *     资源已删除时返回 404；HTTP 幂等性不要求重复请求状态码相同。
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /**
         * 部分更新项目
         * @description Merge Patch：字段缺省表示不修改，description:null 移除成员，
         *     业务层将清除后的 description 在完整响应中规范化为 null。
         *     displayName:null、空对象和未知字段均返回 422。不接受整个文档 null。
         *     If-Match 必须等于当前强 ETag，否则返回 412。校验与写入必须原子化。
         *     每次成功接受的 PATCH（包括同值赋值）递增 version，并更新 updatedAt。
         */
        patch: operations["updateProject"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TraceId: string;
        /** Format: uuid */
        ProjectId: string;
        VersionETag: string;
        /**
         * @description 1 至 100 个 Unicode 码点，至少一个不属于 pattern 中显式空白集合的字符；
         *     不自动 trim。不依赖各编程语言 \s/\S 的差异定义。
         */
        DisplayName: string;
        /** @description 最多 2000 个 Unicode 码点；空字符串与 null 区分 */
        Description: string | null;
        CreateProject: {
            displayName: components["schemas"]["DisplayName"];
            description?: components["schemas"]["Description"];
        };
        UpdateProject: {
            displayName?: components["schemas"]["DisplayName"];
            description?: components["schemas"]["Description"];
        };
        Project: {
            id: components["schemas"]["ProjectId"];
            displayName: components["schemas"]["DisplayName"];
            description: components["schemas"]["Description"];
            /**
             * Format: date-time
             * @description UTC RFC 3339 时间，创建后不可变
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description UTC RFC 3339 时间
             */
            updatedAt: string;
            /** @description JS 安全整数；强 ETag 对应版本，每次成功 PATCH 原子递增 */
            version: number;
        } & {
            [key: string]: unknown;
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            nextCursor: string | null;
        } & {
            [key: string]: unknown;
        };
        ValidationError: {
            /** @enum {string} */
            location: "body" | "query" | "path" | "header";
            /** @description 在对应 location 容器内的 RFC 6901 JSON Pointer；根为 "" */
            pointer: string;
            code: string;
            message: string;
        } & {
            [key: string]: unknown;
        };
        Problem: ({
            /**
             * Format: uri
             * @description 稳定问题类型 URI；部署前配置到自有文档域名
             */
            type: string;
            title: string;
            /** @description 必须与实际 HTTP 状态码一致 */
            status: number;
            /** @description 安全的人类可读说明，不包含堆栈、SQL、令牌或内部地址 */
            detail?: string;
            /**
             * Format: uri-reference
             * @description 不含敏感请求参数的问题实例标识
             */
            instance?: string;
            /** @description 客户端用于分支判断的稳定业务码；未知值回退通用处理 */
            code: string;
            /** @description 服务端分配的请求链路标识，不能作为授权凭证 */
            traceId: components["schemas"]["TraceId"];
            errors?: components["schemas"]["ValidationError"][];
        } & {
            [key: string]: unknown;
        }) & unknown;
    };
    responses: {
        /** @description JSON 语法/重复键、参数、游标、必填 Idempotency-Key 或 If-Match 格式错误 */
        BadRequest: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/bad-request",
                 *       "title": "Invalid request",
                 *       "status": 400,
                 *       "code": "BAD_REQUEST",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 缺少或无效访问令牌；缺少令牌时 challenge 不附 error 字段 */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                /**
                 * @description 缺少令牌用 Bearer realm="projects"；无效令牌可附 error="invalid_token"
                 * @example Bearer realm="projects"
                 */
                "WWW-Authenticate": string;
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/unauthorized",
                 *       "title": "Authentication required",
                 *       "status": 401,
                 *       "code": "UNAUTHORIZED",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 已认证但缺少所需 scope 或无租户操作权限；对象不可见统一返回 404 */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/forbidden",
                 *       "title": "Permission denied",
                 *       "status": 403,
                 *       "code": "FORBIDDEN",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 项目不存在或对当前授权上下文不可见 */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/not-found",
                 *       "title": "Project not found",
                 *       "status": 404,
                 *       "code": "NOT_FOUND",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description IDEMPOTENCY_KEY_REUSED 表示同键不同指纹，须停止自动重试；
         *     IDEMPOTENCY_IN_PROGRESS 表示原请求未完成，稍后可使用原键重试。
         */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                /**
                 * @description 仅 IDEMPOTENCY_IN_PROGRESS 响应必须发送，单位整数秒；REUSED 不提供重试建议
                 * @example 3
                 */
                "Retry-After"?: string;
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description If-Match 与当前 ETag 不一致；重新读取后由用户或业务策略合并 */
        PreconditionFailed: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/precondition-failed",
                 *       "title": "Resource version changed",
                 *       "status": 412,
                 *       "code": "PRECONDITION_FAILED",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 请求 Content-Type 不受支持；POST 要求 application/json，PATCH 要求 application/merge-patch+json */
        UnsupportedMediaType: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/unsupported-media-type",
                 *       "title": "Unsupported media type",
                 *       "status": 415,
                 *       "code": "UNSUPPORTED_MEDIA_TYPE",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 请求体 JSON 合法，但字段类型、必填项、未知字段或业务校验失败 */
        ValidationFailed: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/validation-failed",
                 *       "title": "Request validation failed",
                 *       "status": 422,
                 *       "code": "VALIDATION_FAILED",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736",
                 *       "errors": [
                 *         {
                 *           "location": "body",
                 *           "pointer": "/displayName",
                 *           "code": "REQUIRED",
                 *           "message": "displayName is required"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 缺少必填的 If-Match 请求头 */
        PreconditionRequired: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/precondition-required",
                 *       "title": "If-Match header is required",
                 *       "status": 428,
                 *       "code": "PRECONDITION_REQUIRED",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 超出主体/租户速率或并发配额 */
        TooManyRequests: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Retry-After": components["headers"]["RetryAfter"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/rate-limited",
                 *       "title": "Too many requests",
                 *       "status": 429,
                 *       "code": "RATE_LIMITED",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 服务端未预期错误；客户端不得根据 detail 内容分支 */
        InternalError: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/internal-error",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "code": "INTERNAL_ERROR",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 临时过载、维护或依赖不可用；写操作的实际提交结果可能未知 */
        Unavailable: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "Retry-After": components["headers"]["RetryAfter"];
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.example.com/problems/unavailable",
                 *       "title": "Service temporarily unavailable",
                 *       "status": 503,
                 *       "code": "UNAVAILABLE",
                 *       "traceId": "4bf92f3577b34da6a3ce929d0e0e4736"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description 项目 UUID，按规范小写字符串传输
         * @example 6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c
         */
        ProjectId: components["schemas"]["ProjectId"];
        /**
         * @description 单页上限，服务端必须显式实现缺省值 20
         * @example 20
         */
        Limit: number;
        /**
         * @description 不透明游标；首次请求省略，客户端不得解析或构造
         * @example eyJwb3MiOiJleGFtcGxlIn0.signature
         */
        Cursor: string;
        /**
         * @description 每个逻辑创建操作生成一个高熵随机标识，例如 UUIDv4；网络重试复用同一值。
         *     自定义随机值建议至少 128 位熵；UUIDv4 包含 122 个随机位。
         *     缺失或格式不合法返回 400。本项目采用不加引号的 ASCII header 值协议。
         * @example 7ce2f671-36d4-4756-863b-4e7c225d4a31
         */
        IdempotencyKey: string;
        /**
         * @description 单个强 ETag，例如双引号包裹的版本号 "1"。缺失返回 428，
         *     格式无效、弱 ETag、列表或 * 返回 400，合法但不匹配返回 412。
         * @example "1"
         */
        IfMatch: components["schemas"]["VersionETag"];
    };
    requestBodies: never;
    headers: {
        /**
         * @description 服务端为本次请求分配的 32 位小写十六进制非全零标识，浏览器可用于反馈故障。
         *     新生成错误与正文 traceId 相同；终态错误回放保留原正文 traceId，
         *     本头仍标识当前请求，服务端日志记录本次与历史请求的关联。
         * @example 4bf92f3577b34da6a3ce929d0e0e4736
         */
        RequestId: components["schemas"]["TraceId"];
        /**
         * @description 必须是对应响应体 version 的强验证器，例如 version=1 对应 "1"。
         *     同一资源相同 version 的表示字节必须稳定；更改表示或编码策略应更换验证器。
         * @example "1"
         */
        ETag: components["schemas"]["VersionETag"];
        /**
         * @description 本项目默认禁用浏览器及共享缓存保存响应
         * @example no-store, no-transform
         */
        NoStore: "no-store, no-transform";
        /**
         * @description 本项目固定使用整数秒；客户端加入抖动并受总超时和重试上限约束
         * @example 3
         */
        RetryAfter: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                /**
                 * @description 单页上限，服务端必须显式实现缺省值 20
                 * @example 20
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description 不透明游标；首次请求省略，客户端不得解析或构造
                 * @example eyJwb3MiOiJleGFtcGxlIn0.signature
                 */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表；无数据时 items=[] 且 nextCursor=null */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c",
                     *           "displayName": "示例项目",
                     *           "description": null,
                     *           "createdAt": "2026-09-14T08:00:00Z",
                     *           "updatedAt": "2026-09-14T08:00:00Z",
                     *           "version": 1
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 每个逻辑创建操作生成一个高熵随机标识，例如 UUIDv4；网络重试复用同一值。
                 *     自定义随机值建议至少 128 位熵；UUIDv4 包含 122 个随机位。
                 *     缺失或格式不合法返回 400。本项目采用不加引号的 ASCII header 值协议。
                 * @example 7ce2f671-36d4-4756-863b-4e7c225d4a31
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "displayName": "示例项目",
                 *       "description": null
                 *     }
                 */
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description 创建成功；重复提交可重放最初的 201 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    /**
                     * @description 新资源的相对路径
                     * @example /v1/projects/6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c
                     */
                    Location: string;
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c",
                     *       "displayName": "示例项目",
                     *       "description": null,
                     *       "createdAt": "2026-09-14T08:00:00Z",
                     *       "updatedAt": "2026-09-14T08:00:00Z",
                     *       "version": 1
                     *     }
                     */
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 项目 UUID，按规范小写字符串传输
                 * @example 6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c
                 */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c",
                     *       "displayName": "示例项目",
                     *       "description": null,
                     *       "createdAt": "2026-09-14T08:00:00Z",
                     *       "updatedAt": "2026-09-14T08:00:00Z",
                     *       "version": 1
                     *     }
                     */
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 单个强 ETag，例如双引号包裹的版本号 "1"。缺失返回 428，
                 *     格式无效、弱 ETag、列表或 * 返回 400，合法但不匹配返回 412。
                 * @example "1"
                 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                /**
                 * @description 项目 UUID，按规范小写字符串传输
                 * @example 6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c
                 */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功，无响应体 */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
            428: components["responses"]["PreconditionRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 单个强 ETag，例如双引号包裹的版本号 "1"。缺失返回 428，
                 *     格式无效、弱 ETag、列表或 * 返回 400，合法但不匹配返回 412。
                 * @example "1"
                 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                /**
                 * @description 项目 UUID，按规范小写字符串传输
                 * @example 6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c
                 */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "description": null
                 *     }
                 */
                "application/merge-patch+json": components["schemas"]["UpdateProject"];
            };
        };
        responses: {
            /** @description 更新后的完整项目 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    /**
                     * @description 对应更新后 version 的强 ETag
                     * @example "2"
                     */
                    ETag: components["schemas"]["VersionETag"];
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "6c1d9950-8fa5-4c0e-bb8f-d875fe4c4e7c",
                     *       "displayName": "示例项目",
                     *       "description": null,
                     *       "createdAt": "2026-09-14T08:00:00Z",
                     *       "updatedAt": "2026-09-14T08:10:00Z",
                     *       "version": 2
                     *     }
                     */
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
}
